---
# Repository configuration for wetransform managed repositories

# Reference presets that should apply to this repository
presets:
  - dockerfile
  - renovate
  - workflows-default

check:
  inputs:
    image: wetransform/zip

publish:
  inputs:
    image: wetransform/zip

release:
  inputs:
    image: wetransform/zip

