---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@39472b0820006f75ebd19b348939b163d7bd8a6a # v3.3.2
    with:
      image: wetransform/zip
      tag: pr
